remeda/remeda

.prettierrc
package.json
src/_reduceLazy.ts
src/_types.ts
src/chunk.ts
src/clone.test.ts
src/difference.ts
src/drop.ts
src/filter.ts
src/flatten.ts
src/flattenDeep.ts
src/forEach.ts
src/intersection.ts
src/map.ts
src/pathOr.test.ts
src/pathOr.ts
src/pick.test.ts
src/pipe.ts
src/reject.ts
src/take.ts
src/uniq.ts
tsconfig.json

Addresses #5 
These changes allow remeda to compile with `strictNullChecks: true`, and should ensure that functions such as `pick` and `pathOr` will have the same typing behavior no matter if a project has `strictNullChecks` enabled or disabled.
Changes:
- Add `.prettierrc` and exclude `/dist` from test runs. I had to make these changes to get my environment working correctly, but they can be dropped if they aren't helpful.
- Refactor `LazyResult` to work better with `strictNullChecks`.
- Explicitly allow the `object` argument of `pick` to be `undefined` or `null`, matching the `strictNullChecks: false` behavior.
- Allow `pathOr` to select keys that are possibly missing in the object, matching the `strictNullChecks: false` behavior.
- Allow `pathOr`'s `defaultValue` argument to be of any …

Enable strictNullChecks

---

README.md

be more elaborate in the lazy evaluation example, avoid confusion

 be more elaborate in the lazy evaluation example

---

src/clone.ts

Closes https://github.com/remeda/remeda/issues/26
The current version of the clone() function converts the provided
argument to type 'any'. These changes make the cloned version keep the
type of the provided argument

Add typed clone()

---

package.json
src/compact.test.ts
src/compact.ts

I noticed that calling `compact()` didn't actually remove falsy values according to the typings, which is one of the main reasons I use that function in lodash. IE: `_compact((string|undefined)[])` should result in `string[]`. This doesn't change any functionality, just the typings.
Also, I noticed that for `R.uniq`, two typings are provided for the function, `items => items` and `() => items => items`, while compact() just has this single definition. This lead to some confusion in R.pipe, as I had to call `R.uniq()`, but just use `R.compact` without calling it. I feel like we should standardize on one of these, maybe the `R.uniq()` style?

Narrow typings for compact()

---

src/filter.test.ts
src/filter.ts

Currently, the filter function and other functions like reject do not support type guards.
I added some simple overloads to support this feature.
```typescript
// Guard format that I use
function isNumber<T>(data: T): data is Extract<T, number> {
return typeof data === 'number'
}
```
Before
```typescript
const result = filter([1, 2, 3, 'abc', true] as const, isNumber); value is [1,2,3] incorect type 1 | 2 | 3 | 'abc' | true
`
After
```typescript
const result = filter([1, 2, 3, 'abc', true] as const, isNumber); value is [1,2,3] type 1 | 2 | 3
```
This pull request will add this feature only for filter and filter.indexed functions.
In next pull request, I will add this support for reject and other functions that can accept type guards
P.S Please test not only functionality but also types. …
```

Added support for type guards in filter function

---

docs/src/Menu.tsx

I wondered why searching the docs for `map` doesn't show `flatMap` in the results. I believe this fixes the issue.
Fair warning, I haven't actually run the code, the change is so simple I assumed it was safe to submit a PR without in depth testing.
Thanks for remeda, it's awesome to have a typescript first utility library that's tree shaking friendly. ❤️ ❤️ ❤️

Bugfix: Search docs by lower case function names

---

src/difference.ts

Currently the difference function creates a new set with the entire other list for every item in the primary list. This is quite slow when you have large lists, something I noticed while debugging perf on a node backend we use remeda on. 
I've got a sample runkit that shows the problem in a bit of a basic way: https://runkit.com/ritwik/remeda-difference-perf
This can be improved by creating the set once per call to difference.lazy, rather than on each call of the returned function. It should have the same effect since other shouldn't be modified between those calls (unless I'm misunderstanding something).
Let me know if I should be doing anything else for this PR - I've run the tests locally and they pass, and I assume CI will catch anything else? Or if you prefer, I can create a separate …

Improve performance of difference by creating the "other" set once for each lazy

---

src/mapKeys.ts

the type S was actually never used, and the result object always had `any` as value;
now, we can let the result type have the key be whatever we return from the mapping function and the value will stay the same as before
restricting S to extends string | number | symbol will also ensure that the function only returns something that can actually be used as a key in an object

improve types of mapKeys

---

src/index.ts
src/mapValues.test.ts
src/mapValues.ts

closes #77 
similar to the mapKeys function, but the keys stay the same and the value of the object is mapped instead
I opted for inverting the parameters compared to `mapKeys`, because most of the time, you won't need the `key`, but only the `value`, so having it as a first parameter seems better. This is also how [mapValues from lodash](https://lodash.com/docs/4.17.15#mapValues) works.

add mapValues

---

src/index.ts
src/zip.test.ts
src/zip.ts

Per remeda/remeda#72, adds the `zip` utility:
*Data first*
```
R.zip([1, 2], ['c', 'd']) // => [[1, 'c'], [2, 'd']
```
*Data last*
```
R.zip(['c', 'd'])([1, 2]) // => [[1, 'c'], [2, 'd']
```

Add `zip` utility

---

package.json
src/pick.test.ts
src/pick.ts
yarn.lock

Test for existence of object property before including it in returned object. 
As part of this PR I upgraded `jest` and `@types/jest` in order to pick up the `toStrictEqual` matcher (since `toEqual` treats `undefined` the same as nonexistent).
I ran all tests and compiled to confirm no adverse impact of the library upgrades.

[remeda/remeda#81] Do not return nonexistent source properties from pick

---

src/index.ts
src/zipWith.test.ts
src/zipWith.ts

Per #72 adds `zipWith` utility
*Data first*
```
R.zipWith(['1', '2', '3'], ['a', 'b', 'c'], (a, b) => a + b) // => ['1a', '2b', '3c']
```
*Data last*
```
R.zipWith((a, b) => a + b)(['1', '2', '3'], ['a', 'b', 'c']) // => ['1a', '2b', '3c']
```
*Data last with initial arg*
```
R.zipWith((a, b) => a + b, ['a', 'b', 'c'])(['1', '2', '3']) // => ['1a', '2b', '3c']
```

Add zipWith utility

---

src/fromPairs.test.ts
src/fromPairs.ts
src/index.ts

Per #72 adds `fromPairs` utility
```
R.fromPairs([['a', 'b'], ['c', 'd']]) // => {a: 'b', c: 'd'}
```

Add fromPairs utility

---

src/pick.test.ts
src/pick.ts

Previous change used `hasOwnProperty`, which does not support inherited properties.  Using `in` per suggestion in #107 fixes this problem.

[remeda/remeda#107] Restore support for inherited properties with pick

---

src/sortBy.test.ts
src/sortBy.ts

Thank your for this wonderful library!
I often need to be able to specify multiple fields to project a sort on, in addition to parameters. I would like to add this behavior to remeda.
Can be used like:
```ts
const objects = [
{ color: 'red', weight: 2 },
{ color: 'blue', weight: 3 },
{ color: 'green', weight: 1 },
{ color: 'purple', weight: 1 },
];
R.sortBy(objects, x => x.weight, x => x.color);
R.sortBy(objects, [x => x.weight, 'desc'], [x => x.color, 'desc']);
R.sortBy(objects, x => x.weight, [x => x.color, 'desc']);
```

Adds support for multiple sort by projections as well as directions

---

src/addProp.ts
src/forEachObj.ts
src/mapValues.ts
src/omit.ts
src/pick.ts

In this PR I suggest to change the way that generic object types are declared. This is because the way that the project is using them is wrong, let me explain that (all example have links to [TypeScript playground](https://www.typescriptlang.org/)):
- T extending `unknown` type
```typescript
export function addProp<T, K extends string, V>(obj: T, prop: K, value: V) => T & { [x in K]: V }
```
When no types constraint are declared on a generic, TypeScript assumes that the generic type is `unknown`. So according with that, in `addProp` function I can write any type and TypeScript compiler will not alert me, [like that](https://www.typescriptlang.org/play?#code/CYUwxgNghgTiAEAzArgOzAFwJYHtXymGAAUYcAHAHgBUAaeAaXhAA8MRVgBneLjGLKgDm9AGoA+ABQBYAFDx4OAEYArAFzw6cheTLkNDWtvgA3KBGQgNouQEoN1eADJ4Ab3gBt …

Fixes object generic constraints

---

src/last.test.ts
src/last.ts

if a verified non-empty array is passed as input, the result value cannot be potentially undefined

feat(last): improve types

---

src/index.ts

Add missing export of `partition`
Relates to remeda#169

fix(partition): export partition

---

.github/workflows/pages.yml
docs/package.json

Add GH pages build and publishing. Would work only on merge to main branch so we need to use something like Netify for PRs. Example: https://remeda.vlad-yakovlev.dev/
Could be safely merged because current website uses travis & netify
---

chore: Add pages workflow

---

src/last.test.ts
src/last.ts

Fixes: https://github.com/remeda/remeda/issues/177
Adds a test case to handle the scenario covered by the issue.
Removes code copied over from first.ts that forces function last() to behave like first.

fix bug where last was behaving like first on pipe #177

---

src/map.ts

I found the map example with typo.
```typescript
/**
* Map each value of an object using a defined callback function.
* @param fn the function mapper
* @signature
*    R.map(fn)(array)
*    R.map.indexed(fn)(array)
* @example
*    R.pipe([0, 1, 2], R.map(x => x * 2)) // => [2, 4, 6]
*    R.pipe([0, 0, 0], R.map.indexed((x, i) => i)) // => [0, 1, 2]
* @data_last
* @indexed
* @pipeable
* @category Array
*/
export function map<T, K>(fn: Pred<T, K>): (array: readonly T[]) => K[];
```
so I fix the typo from ```R.pipe([0, 1, 2], R.map(x => x * 2)) // => [2, 4, 6]``` to ```R.pipe([0, 1, 2], R.map(x => x * 2)) // => [0,  2, 4]```

fix: fix typo of map example

---

mapping.md

Closes #208
After investigating it appears `sortBy` can imitate `lodash/orderBy` effectively. So I am updating `mapping.md`, thus closing the main issue.
---

docs(mapping.md): orderBy support

---

src/partition.test.ts
src/partition.ts

This PR adds an overload to partition that supports type guards. See the added test for an example.
Before remeda had this function we implemented it like this, it would be nice to merge this and drop our implementation.
```ts
test('partition with type guard', () => {
const isNumber = function (value: any): value is number {
return typeof value === "number"
};
const actual = partition([1, "a", 2, "b"], isNumber);
expect(actual).toEqual([[1, 2], ["a", "b"]]);
const result: AssertEqual<
typeof actual,
[number[], string[]]
> = true;
expect(result).toBe(true);
});
```

feat: add overload to partition with type guard support

---

README.md
docs/src/Home.tsx

Just discovered your library today and really nice work! 
Wanted to update the docs very slightly to make it clearer to new readers that Remeda is in fact a data-last library like one would expect. When I first landed on the README i scanned it looking for code, and when I saw that the Remeda / Ramda examples didn't match I immediately assumed that this wasn't actually data-last support and figured that lodash was sufficient. And then I read it again! And dove into the docs and saw that it does everything I'd like. This update makes that clearer for the new arrival, and particularly the type of new arrival who doesn't read words too closely.

docs(readme): Make data-last support more obvious to new readers

---

src/keys.test.ts
src/keys.ts

fixes https://github.com/remeda/remeda/issues/253
---

fix(keys.strict): remove undefined from returned union type

---

src/toPairs.test.ts
src/toPairs.ts

Similar to `keys`, the existing `toPairs` function strips the typing of the object keys. Taking inspiration and largley copying the work in ts-extra's objectEntries, this version of toPairs will return the strictest type for the entries tuple.
I've added it as a strict option instead of replacing the `toPairs` impl for backwards compatibility and to align with `keys`.
---

feat(toPairs): Add 'strict' flavour

---

src/groupBy.test.ts
src/groupBy.ts

`groupBy` currently doesn't support refined types for it's grouper function, so you lose typing information in cases where those are available.
This diff only touches typing, and doesn't change anything in the runtime behaviour of the function.
It maintains backwards compatibility by still returning `Record<string, T>` if the grouper function returns a string. And for literal unions it will return a Partial record.
I tried adding tests, and they do provide some protection, but I'm not sure I'm using AssertEqual correctly, as it doesn't fail on the wrong types (sometimes). I validated manually via the IDE that the types returned are correct. 
Fixes: #262
---
- [?] Typedoc added for new methods and updated for changed
- [+] Tests added for new methods and updated for …

feat(groupBy): add support for generic key types

---

src/noop.ts

The `as any` has bad results when it comes to inferring result types in anything actually expecting or differentiating on `undefined`. It's better for type inference purposes to just let the return type be `undefined`.

Change noop return typing to just 'undefined'

---

tsconfig.build.json

Including extra files from the parent directory in tsconfig means that tsc will build everything under the folder it lives in. By only taking files from `src` tsc considers it the root directory and doesn't create it as a subdir.

fix(build): Refine build directory

---

src/first.test.ts
src/first.ts

There are several situations were the type of the first value could be inferred more precisely than just `T[0] | undefined`; when the array is not empty, and when taking into consideration arrays used as tuples too.
---

fix(first): better typing

---

src/_types.ts
src/fromPairs.test.ts
src/groupBy.test.ts
src/guards.test.ts
src/keys.test.ts
src/last.test.ts
src/omitBy.test.ts
src/partition.test.ts
src/pickBy.test.ts
src/reverse.test.ts
src/toPairs.test.ts
src/zip.test.ts
src/zipWith.test.ts

See https://github.com/remeda/remeda/pull/238#issuecomment-1383131398
Basically, use the `expectType` function of `ts-expect` to check for types instead of the bespoke checking that was there. Technically it does the same thing, the syntax is just a wee bit shorter.

move to vitest's assertType

---

src/_types.ts
src/pathOr.ts

These aren't generic, they should be colocated with the code that uses them. Also, Keys was just a redefinition of PropertyKey from Typescript.

chore: types

---

src/groupBy.ts

Fix typo in groupBy example
---

docs: fix typo in groupBy example

---

.github/workflows/ci.yml
package.json
yarn.lock

Instead of relying on the package using a specific typescript version to stay backwards compatible, we can run a set of tests on old typescript versions instead.
This allows us to update typescript regularly, enjoy any QoL improvements, and still ship backwards compatible code (and even know what the bare minimum version of typescript we actually need to ship).
(Largely copied from https://github.com/sindresorhus/type-fest/blob/main/.github/workflows/main.yml#L24-L41)

ci: Test typescript versions

---

src/chunk.test.ts
src/chunk.ts

The previous Chunked definition wasn't good for regular plain arrays as it's output wasn't a simple array (it was the union  `[] | NonEmptyArray<...>`). 
Typescript didn't handle this correctly when the Chunked result was needed in a function that took a simple array.
This typing results in a simpler output.
I also rewrote the tests to cover more cases and be pure type testing, without runtime checks

fix(chunk): Simplify general case

---

mapping.md
src/index.ts
src/join.test.ts
src/join.ts

Adding a better typed wrapper around the builtin Array.prototype.join, with data-first and data-last signatures.
Similar to https://github.com/sindresorhus/type-fest/blob/main/source/join.d.ts
---

feat: join utility

---

src/prop.test.ts
src/prop.ts

change the type to be able to deal with the standalone form (where we don't know the source object type at all) and the form used in `pipe` (where we have an inference of the source).
For #320

improve on the type of prop

---

src/prop.test.ts
src/prop.ts

I've encountered issues at work were prop didn't detect the object's props and didn't offer typehints, allowing entering any propName, and resulting in `any` in the pipe instead of a strict type.
I don't fully understand when this happens and when it doesn't, as it doesn't repro in all pipes (as can be seen by the test), but generally, if the prop function right now doesn't provide us a strong type-safety at compile time to prevent people from accessing a non-existent prop then it isn't useful.
Reverting to the typing before #238

fix(prop): strict key names

---

mapping.md
src/index.ts
src/length.test.ts
src/length.ts

> Adds simple `length` operator
---

feat: length

---

src/times.ts

The examples for `times` passes the function arguments in the wrong order.
> The example in the the docs lists the parameters as `times(identity, 5)` (function before count). However, the code itself expects `times(5, identity)` (count before function). This change updates the example to match the code. This PR also changes the docs for the data-first version of times.
---

Update documentation for times.ts

---

src/omit.test.ts
src/omit.ts

In hot paths where the omit is used to filter out props which are rare (like normalization paths) the current impl creates too many redundant objects both while computing the omit (the set and the new object) and for the output.
In this implementation the object is only created if needed.
We also optimize the case of a single prop to remove to use spread so that the effort of creating the new object is left to the engine, instead of our impl.
Finally, we implement the the omit via built-ins so that we don't need to deal with our own loops. This might be optimized by the engine (at least when we move to more modern es versions)

chore(omit): Optimized for optional keys

---

src/swapProps.ts

> Fixed missing description for `swapProps`
---
Hello, I noticed that the description for `swapProps` was hot showing up in the docs (https://remedajs.com/docs#swapProps):
I fixed it and added the "Object"-tag:
Cheers

docs(swapProps): Missing description for data_first version + category

---

src/drop.test.ts
src/dropLast.test.ts
src/dropLast.ts

Closed https://github.com/remeda/remeda/issues/350
Added a pinch of tests.
Also this change fixed the work with `NaN` as `N`.

fix(dropLast): Handle non-positive lengths

---

.github/workflows/pages.yml

I recently created a project deployed to github pages and followed their guide. I ported those recommendations here too.
Also changed the trigger to relases so that our docs don't reflect changes that aren't part of the library yet (for the rare cases where we ship something to the `master` branch but don't relase a version soon after.

ci(docs): modernize docs release

---

src/isEmpty.test.ts
src/isEmpty.ts

Adds support for undefined for strings (but not for arrays and objects).
Closes #369 
---

type(isEmpty): accept undefined for strings

---

.github/pull_request_template.md
.github/workflows/pr_titles.yml

We rely on PR titles for our release process, we usually need to rename PRs manually to make them fit, and we often make mistakes.
This should prevent all that

ci: lint PR titles for conventional syntax

---

src/zip.test.ts
src/zip.ts

Inspired by https://github.com/remeda/remeda/issues/389, this PR will add a strict version to the data-first version of `zip`, which, given two finite (non-variadic) tuple types, will return another finite tuple type instead of a wider array type.
```ts
R.zip([1, 2], ['a', 'b'])
// => [[1, 'a'], [2, 'b']] (type: [1 | 2, 'a' | 'b'][])
R.zip.strict([1, 2] as const, ['a', 'b'] as const)
// => [[1, 'a'], [2, 'b']] (type: [[1, 'a'], [2, 'b']])
```
I couldn't come up with a strict version of the data-second version, and while I'm not sure that it makes sense to have only one strict version, it is quite useful anyway.
If the maintainers decide that it make sense, I'll probably expand this PR to have strict versions of `zipWith` and `zipObj`, too. If that's not the case, maybe this PR can be a …

feat(zip): strict tuples

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
lint-staged.config.js
package.json

A few changes to our scripts and build process to make things a little faster and more ergonomic:
* Don't collect coverage data in regular test runs
* Don't run typechecking (building?) during test runs
* Do typechecking on the commit hook (instead)
* bump version of typechecking github action (following the release of ts 5.3)
* cleanup lint-staged to run on any prettier supported file (extendable with plugins) instead of a fixed set.

build: split coverage and typechecking from testing

---

vitest.config.ts

The upgrade to vitest v1 meant that the definition of what's included in the coverage report changed. This caused us to report files that are not part of the module and that caused our score to go down.
This defines just the files we want to export to users for the coverage report.

chore: define files for coverage repors

---

docs/scripts/transform.ts

So that JSDocs of functions can be formatted on multiple lines without affecting the docs site. Double line breaks will still be rendered as a new paragraph.
This is done by disabling the GFM (GitHub flavored markdown) style of line breaks when parsing the function descriptions with the 'marked' package.

docs: Disable single line breaks in docs site

---

src/add.ts
src/divide.ts
src/multiply.ts
src/subtract.ts

Those 4 [relatively new functions](https://github.com/remeda/remeda/pull/443) have a small issue in their data-last signature - they all show `R.clamp` instead of the actual function name. This PR fixes this issue.
---
_[does not apply probably]_
---
- `refactor`: …

docs: fix signatures for `add`, `divide`, `multiply` and `subtract`

---

docs/src/Menu.tsx

This PR adds different badge colors per each function type in the side menu. The goal is to make finding the right function easier.
Note: color choices are very arbitrary, I'm open to suggestions.
Example:
---
_[does not apply probably]_
---
- `refactor`: changes to …

docs: use multiple badge colors in menu

---

src/isArray.test.ts
src/isArray.ts

It took me a while to figure out what was causing the issue or how to fix it. I'm still not sure I understand.
Fixes #459

fix(isArray): handle inferrence of ReadonlyArray inside an array

---

docs/src/pages/index.astro

Fixes indentation and semicolons in the examples on the home page

fix(docs): fix examples indentation

---

docs/.eslintrc.cjs
docs/.vscode/settings.json
docs/README.md

To allow using prettier via vscode directly in the docs project we need to add a new settings file. then, when opening the vscode project directly from the docs folder (code docs/) in the terminal all tools work correctly with the correct settings.

docs: enable prettier for sub-project

---

docs/src/components/mobile-nav.tsx
docs/src/components/navbar.tsx

Because **react-remove-scroll** causes a reflow and /docs page is huge, sidebar opens really slow in modal mode.
Also changed hrefs in navbar so links work correctly from home page.

docs: improve sidebar opening perf by disabling modal mode

---

mapping.md
src/index.ts
src/only.test.ts
src/only.ts

closes #467 
i don't think `only` can be made lazy; here's the argument. when called with a value, we either:
* return it immediately as `next`. later if we get another value we can't "take back" the value we gave before
* don't return it as `next`. but then we don't get called again, so there's no way for the caller to get the value
there are changes that can be made to the architecture to allow it to be lazy. the one that needs least changes, i think, is to change `pipe` to be
```diff
if ((lastLazySeq as any).single) {
-      ret = acc[0];
+      ret = acc[acc.length - 1];
} else {
ret = acc;
}
```
this lets `only` "take back" a value it returned, and replace it with `undefined` (and, surprisingly to me, all tests pass after this change). i don't like it though
--- …

feat(only): Add `only`

---

eslint.config.js
src/_purryOn.ts
src/_purryOrderRules.ts
src/clone.test.ts
src/clone.ts
src/conditional.ts
src/debounce.ts
src/flattenDeep.ts
src/forEachObj.test.ts
src/isArray.test.ts
src/isBoolean.test.ts
src/isObjectType.test.ts
src/isPlainObject.test.ts
src/isPlainObject.ts
src/isSymbol.test.ts
src/pathOr.ts
src/pick.test.ts
src/pipe.ts
src/purry.test.ts
src/purry.ts
src/setPath.ts
tsconfig.json

Continuing to clean up and strictify the codebase by removing any `any`, using eslint to guide me.
The main change here (and the reason i'm adding a "fix" type so that we bump a version) is the changes to purry/pipe, including changing the compilation flag to allow iterating in es5

fix: remove more `any` from the codebase

---

src/fromPairs.test.ts
src/fromPairs.ts
src/keys.test.ts
src/keys.ts
src/randomString.ts
src/toPairs.test.ts
src/toPairs.ts
src/values.test.ts
src/values.ts

I can't think of a way to support the headless versions in tandem with adding the dataLast implementations, typescript considers the function a completely different "thing" once we have the dataLast overload and doesn't fallback to the dataFirst variant inside the pipes.
Blamed on #531
Fixes #539

feat(values,keys,fromPairs,toPairs): Remove dataLast impls (reverts #531)

---

src/chunk.ts

optimized `_chunk()` by cached array length and accumulative multiplication.
About cached array length: https://dev.to/akashkava/javascript-does-not-cache-array-length-2n65
---
---
- …

fix(chunk): improve runtime perf

---

docs/src/lib/transform.ts
src/purry.ts

We don't need this special casing of the purry example, everything works fine without it, and exampleRaw isn't a standard JSDoc tag so it's just messy.

docs: remove exampleRaw tag

---

eslint.config.mjs
src/difference.ts
src/index.ts
src/intersection.ts
src/isIncludedIn.test.ts
src/isIncludedIn.ts
src/mapWithFeedback.ts

A type-guard that checks existence in a set of values. Useful for narrowing possible enum (literal union) values via a global const.
Optimizes dataFirst and dataLast implementations offering better performance for each case.
Deprecated intersection and difference in favour of using filter in combination with isIncludedIn so we can take advantage of the performance gains and optimizations, and to make room for future interestion and difference functions which will work more closely to the mathematical definitions of multi-sets (which take into account duplicate items, as could be present in arrays). See #368 
---
---
PRs should be titled following using …

feat: isIncludedIn

---

mapping.md
src/equals.ts
src/index.ts
src/isDeepEqual.test.ts
src/isDeepEqual.ts

Largely copied from `equals` and then modified to:
* Enforcing the types overlap so that changes that would cause the function always to return `false` would be detected as compile errors.
* Making the function a guard against the second param, allowing it to be used as a type-narrower against the second param.
* Checking the object prototype, identifying mismatches early on, and taking advantage of this to perform fewer checks.
---
---
- `fix`: changes to the runtime behavior of an …

feat(isDeepEqual): replace `equals` with `isDeepEqual`

---

src/merge.test.ts
src/merge.ts
src/type-fest/merge.ts

Our existing typing assumes that the 2 merged objects either share a type, or have types that don't overlap; and fail for cases where a merged property changes the type of the input.
We already have the type-fest merge type in our codebase (used in deepMerge) so we just need to change the typing for merge.
I added all the type tests from type-fest.
---
---
- …

fix(merge): Allow overriding types

---

.travis.yml
README.md

Our tag in the readme shows that the service is unavailable, and the status of the travis integration in github shows that the endpoint is getting 503 requests. It also still uses node 10(?!) so i'm guessing this is some legacy thing that isn't even working anymore.

chore: drop Travis CI

---

src/invert.ts

Fix typo in `invert` description

docs(invert): fix typo in description

---

src/product.ts

Very minor typo fix in jsdoc for datalast `product` function.

docs(product): wrong return value in example

---

src/dropLastWhile.ts
src/dropWhile.ts
src/flatMap.ts
src/fromKeys.ts
src/indexBy.ts
src/mapKeys.ts
src/mapValues.ts
src/omitBy.ts
src/pickBy.ts
src/pullObject.ts
src/splitWhen.ts
src/takeLastWhile.ts
src/takeWhile.ts
src/uniqueBy.ts
src/zipWith.ts

Adding the params needed to make all predicate/mapper functions conform to the standard where we include the index and the full array as the last 2 params.

feat: add indexed versions

---

src/constant.ts
src/debounce.test.ts
src/doNothing.ts
src/dropFirstBy.test.ts
src/filter.test.ts
src/firstBy.test.ts
src/identity.ts
src/map.test.ts
src/meanBy.test.ts
src/nthBy.test.ts
src/pipe.test.ts
src/prop.ts
src/pullObject.test.ts
src/randomString.ts
src/rankBy.test.ts
src/sliceString.ts
src/takeFirstBy.test.ts
src/uniqueBy.test.ts
src/values.ts

Make sure we offer a consistent syntax and convention for dataLast and dataFirst, including making identity dataLast instead of headless.

feat: Improve consistency for dataLast/dataFirst usage

---

.github/workflows/ci.yml
src/debounce.ts
src/join.test.ts
tsconfig.dist.json
tsconfig.json

Just doing this change and following up on any errors and warnings

feat(v2): bumping typescript target and library to es2022

---

eslint.config.js
src/conditional.ts
src/differenceWith.ts
src/drop.ts
src/first.test.ts
src/first.ts
src/flatMap.ts
src/flatten.ts
src/flattenDeep.ts
src/intersectionWith.ts
src/isIncludedIn.ts
src/purry.ts
src/take.ts
src/unique.ts

Simpliyfing the purry/pipe model by removing direct "lazy" extending. It wasn't used directly anyway, as purry always "made sure" to bridge the gap for any other function anyway

fix: remove lazy from function impl

---

package.json

When trying out the beta I encountered issues with importing remeda in next.js.
This is ChatGPTs suggestions for a fix... ¯\_(ツ)_/¯

fix(build): remeda fails to import in next.js

---

package-lock.json
package.json

We need to make sure type-fest is also installed whenever remeda is installed so that the types could be used.

fix(build): make type-fest a depedency so it's always installed for users

---

src/findLast.ts
src/findLastIndex.ts
src/reverse.ts
src/sortBy.ts
src/splice.ts
tsconfig.json

Node 18's last API version is ES2022, and being LTS it would be supported until May 2025, this gives us an expiry date for these TODOs

chore: Update node18 related TODOs

---

src/isIncludedIn.test.ts
src/isIncludedIn.ts
src/type-fest/internal.ts
src/type-fest/is-literal.ts
src/type-fest/is-never.ts
src/type-fest/numeric.ts
src/type-fest/primitive.ts

Because of limitations of how typescript handles literal unions (and the lack of ability to detect them in the typing system) certain cases narrow the negated case too aggressively.
e.g. If our data is of type `1 | 2 | 3` and our container is `Array<1 | 2>` we can say that the data could be narrowed to `1 | 2`, but we can't say that the negated case could be narrowed to `3` because the container array could still be empty.
I couldn't find a way to tell Typescript to narrow only the successful result without impacting the negative one, so we can only reduce the "surface" for the narrowing variant of the function to those that make the most sense. Even with this, there are erroneous cases, but at least they are reduced to a very small subset.
Fixes: #603

fix(isIncludedIn): Only narrow on exact cases

---

src/isIncludedIn.test.ts
src/isIncludedIn.ts
src/type-fest/internal.ts

Type-fest has a `IsUnion` utility, this allows us to avoid the only known caveat our type previously had.

fix(isIncludedIn): handle literal unions

---

src/evolve.ts

Tiny change to the `evolve` description.
I got confused as to what happens to values in `obj` when the corresponding key is not included in `evolver` and had to actually check the source code to figure it out. Examples are correct, but the original phrasing made it sound like they might be getting stripped away ("unused"). 
---
---
- `perf`: changes to function …

docs(evolve): Clarify what happens to unused values in `evolve`

---

src/hasAtLeast.test.ts
src/hasAtLeast.ts

Initially I thought this fix would have to wait for v2 because I wanted to disable the guard from working on non-literal numbers.
With the recent work I did for `isIncludedIn` I realized that we can simply "turn off" the guard-ness for those cases.
With this solution this change could be considered a fix and not a breaking change, so could be merged into v1.

fix(hasAtLeast): dont narrow on non-literal minimum

---

src/pathOr.ts

`pathOr` actually returns `defaultValue` when the returned value at path is nullish, not just `undefined`
---
---
- …

docs(pathOr): Fix minor mistake in `pathOr` docs

---

src/first.test.ts
src/last.test.ts
src/last.ts
src/type-fest/last-array-element.ts

An attempt to consolidate typings and some naming conventions between `first` and `last`. I tried catching all cases with tests but let me know if you spot a problem that might be solvable.
Would it be beneficial to have a look at typings for `take` and `drop` in a similar manner?
---
---
- `perf`: changes to function implementations that improve a functions …

fix(last): Improve `last` typings for tuples

---

src/firstBy.ts

> R.pipe([1,2,3], R.firstBy([1,2,3]))
_purryOrderRules.js:53 Uncaught TypeError: Cannot read properties of undefined (reading '0')
---
---
- `test`: tests-only changes (transparent to …

Fix firstBy.ts example

---

src/isDeepEqual.test.ts
src/isDeepEqual.ts

Fixes: #634
Narrowing the result of isDeepEqual is redundant when the type isn't effectively narrowed because it breaks the rejected/negated path which would be `never`.
This means that the common use case where both objects are of the same type and narrowing was meaningless, will now act as a regular boolean check.

fix(isDeepEqual): Prevent redundant narrowing

---

src/stringToPath.test.ts
src/stringToPath.ts

Tests only covered paths with single-character keys. While the implementation works correctly even for longer keys, types were actually inferred wrong:
```ts
const path = R.stringToPath("foo.bar");
// ^?  would be ["f", "o", "o", "b", "a", "r"]
```
Reworked the `StringToPath` type and added tests covering more broad edge-cases.
I am not entirely clear why the "handles dot paths inside bracket access" is necessary, or even why it makes sense, since e.g. `"foo[bar.baz]"` is not a valid object path. 
I'm not sure if `pathOr` resolves an array access (or how), but even ignoring this was created to support `pathOr`, shouldn't we only allow integers between `[` and `]`, and potentially parse them out as numbers too? 🤔 
---
---
<details><summary>We use semantic PR titles to …

fix(stringToPath): Fix broken types for `stringToPath`

---

docs/src/components/function-card.astro

<details><summary>Added media query for card header to fix content overflow</summary>
While reading docs on my iPhone I've noticed that the menu at the top of the page is shorter than the page itself.
This happens due to overflow of `<CardHeader />`. When there is 3 tags and the github badge then whole row goes wider then the screen.
So I added media query for screens that is wider than `sm` breakpoint.
</details>

docs(card): fix card header overflow

---

docs/src/content/v1-migration/clone.md
package-lock.json
package.json
src/clone.test.ts
src/clone.ts

I'm procrastinating releasing v2 so in the meantime I took a look at clone.
I deprecated the support for `.clone()` function inside the cloned object. It wasn't part of the documentation and felt like it doesn't fit in the library.

fix(v2): rewrite clone

---

.github/workflows/ci.yml
.github/workflows/codecov.yml
README.md
docs/typedoc.json

main has been checked out from the 'beta' branch so now represents the HEAD for v2 and remeda in general.
This PR makes the CI treat main as a valid branch for releases. by making it breaking it would de-facto release v2.
BREAKING CHANGE: Releases Remeda v2.

build(v2): Switch CI to use main instead of master

---

docs/src/components/header.astro
docs/src/components/nav-link.astro
docs/src/layouts/docs-page.astro
docs/src/layouts/wiki.astro

When viewed on mobile the docs page extends beyond the "frame", skewing the layout.
Merging into `master` until we can get the deployment fixed.

docs: Fix mobile view

---

docs/src/pages/index.mdx

Fixes Array .map example in docs home page to use valid js
---
---
- `docs`: changes to the documentation of a …

docs: Update .map example in docs home page

---

.github/workflows/codecov.yml

Following the guide from codecov:
https://docs.codecov.com/docs/adding-the-codecov-token#github-actions

chore(codecov): Add secret to action

---

src/mapValues.test.ts

Noticed that #684 is labeled as good first issue so I gave it a try. I enhanced `mapValues` tests by adding a case for branded types used as record keys.
I would be happy to make any further adjustments as needed.
---
---
- `refactor`: changes to function …

test(mapValues): add tests for using branded types as record keys

---

src/internal/types.ts
src/omitBy.test.ts
src/omitBy.ts
src/pickBy.test.ts
src/pickBy.ts

Closes: #696
When making a Record/indexed-object partial `undefined` is added to the value type. This is incorrect when using exactOptionalProperties because `undefined` is not a valid value and would never show up, making the result type too wide.
By checking specifically for string and number keys (and their combination) we can rebuild the output object differently for those cases.

fix(pickBy,omitBy): Don't partialize simple records

---

src/debounce.ts
src/firstBy.ts
src/nthBy.ts
src/times.ts

Headless invocation of identity has been removed. This PR makes sure that the docs are aligned with this change.
Fixes: #709

docs(identity): Remove headless identity invocations from examples

---

docs/.gitignore
docs/package-lock.json
docs/package.json
docs/src/layouts/base.astro
docs/src/scripts/README.md
docs/src/scripts/init-theme.ts
docs/tsconfig.json
docs/vite.scripts.config.ts

Our initTheme function was running after the page already rendered, causing it to flicker with lightMode no matter what mode you were on.
This is a holisitc approach to providing us a way to load scripts synchronosly wihle the page loads.

docs(darkMode): Stop light mode flickering on load

---

src/addProp.test.ts
src/addProp.ts
src/internal/types.ts
src/set.test.ts
src/set.ts
src/setPath.ts

The current type would allow setting an optional prop with `undefined` even when it isn't a valid value for the prop.
I also expanded the typing to make the output more useful by making optional props required and have a fixed value (when possible).

fix(set): prevent setting `undefined` on optional props

---

src/join.ts
src/swapIndices.ts

We don't provide types in our exports, only functions.  It was only exported because it was shared in 2 different functions.
The type itself was written before we had type-fest integrated into the library, and is a copy of the Join type in type-fest (which I contributed when I wrote the type), so I consolidates it's usage.

fix(join): Remove Joined type export

---

src/pipe.test.ts
src/pipe.ts

Currently when using `pipe`, `take` does nothing if it is followed by `flat` or `flatMap`. Here is a small example:
```ts
import * as R from 'remeda';
console.log(
R.pipe(
[
[1, 2],
[3, 4],
[5, 6],
],
R.take(1),
R.flat()
)
);
```
This code should output to the console `[1, 2]`, but actually outputs `[1, 2, 3, 4, 5, 6]`
This is because using `take` causes `isDone` to change to `true`, but `flat` (or any other function with `hasMany` in its iterator) has an early return of `false`, that ignores the value of `isDone` (so, instead of taking only first pair in the example code, `pipe` will take all pairs)
---
---
PRs should be titled following using the …

fix(pipe): early exit on hasMany

---

src/hasSubObject.test.ts
src/hasSubObject.ts
src/internal/types.ts

Fixes: #678
The only way I come up to fix the issue with the negate condition in case when the guard resolves to the same type as `data` is by using something that will make the guard always different from `data`. One solution can be by using a brand type. Brand type is an internal type that doesn't affect anything but can help us identify the type result better. The users of the library can safely ignore that brand type.
This is the first occurrence of a brand type so let me know if I need to change its format/naming, etc.
Next, in a separate PR, I'm going to try to improve the overall typing of `hasSubObject` to make the narrowing more smarter. I already did some progress but stuck on making it work well with `pipe` function.
---
---
<details><summary>We use semantic …

fix(hasSubObject): incorrect type narrowing in negate condition

---

package.json
src/conditional.ts

Fixes: #720
Copying what I wrote in issue #720:
I managed to reproduce the issue. It bisects to #596, but that makes me think that maybe that PR (that simply fixed a attw linit warning) just surfaced the fact that our ESM build for this function was always broken. I have a hunch that tsup (or esbuild) is not doing a good job with `namespace` by using an IIFE to inject the property instead of `Object.assign`, which is what I would expect would happen.

fix(conditional): Use Object.assign to inject the defaultCase prop

---

src/hasSubObject.ts

**Context:** https://github.com/remeda/remeda/pull/683#discussion_r1630022640
| Before | After
| - | - |
| ![image](https://github.com/remeda/remeda/assets/10157660/8ff6e445-12c0-4efc-a1a7-dcb54b757d46) | ![image](https://github.com/remeda/remeda/assets/10157660/056622d8-edd6-4f01-b25b-1fca33403e2c) |
---
---
- `perf`: changes to function implementations that …

fix(hasSubObject): use `Simplify` type to show better type information

---

src/forEachObj.test.ts
src/internal/types.test.ts
src/internal/types.ts
src/keys.test.ts
src/keys.ts
src/mapKeys.test.ts
src/mapKeys.ts
src/mapValues.test.ts
src/omitBy.test.ts
src/omitBy.ts
src/pickBy.test.ts
src/pickBy.ts
src/values.test.ts

Closes #727.
I thought it was an inference issue so I tried to resolve it by modifying the types and using `infer`. Moreover, I tried to keep using the internal types `EnumerableStringKeyOf` and `EnumerableStringKeyedValueOf`. 
I would be happy to integrate any further adjustments as needed. 
---
---
- `perf`: changes to function implementations that improve a …

fix: key and value typing of unions of object types.

---

src/fromKeys.test.ts
src/fromKeys.ts
src/pullObject.test.ts
src/pullObject.ts

Using the new ExactRecord type, we can refine the type for pullObject and fromKeys so that unbounded keys don't result in wrapping the record with Partial<>

fix(pullObject,fromKeys): Don't partialize unbound records

---

docs/src/content/mapping/lodash/__MISSING.md
docs/src/content/mapping/lodash/split.md
docs/src/content/mapping/ramda/__MISSING.md
docs/src/content/mapping/ramda/split.md
src/index.ts
src/split.test.ts
src/split.ts

Using the type-fest split type, but extending it to support arbitrary strings, and to include the limit param.
---
---

feat(split): Add split

---

src/hasSubObject.test.ts
src/hasSubObject.ts

> This PR depends on https://github.com/remeda/remeda/pull/683. See 35afa2fee17aa0fe16af3d467c18b22fabe23a44 for changes.
**Depends on:** https://github.com/remeda/remeda/pull/683
- make type narrowing smarter
- handle cases with overlapping union types (e.g. `{ a: string | number}, { a: number | boolean }`)
- improve typing for nested objects
---
---
- `perf`: …

feat(hasSubObject): improve typing

---

docs/src/components/docs-page-nav.astro
docs/src/components/header.astro
docs/src/components/migration-selector-island.tsx
docs/src/components/migration-selector.astro

Netlify are rewriting URLs to always have a terminal backslash (/). This breaks the regex we use to detect the migration pages for the mobile nav bar.
I also added some more overflow detection.

docs: Fix mobile navbar

---

src/forEach.test.ts
src/forEach.ts

The current implementation takes T as the array item type, and not the array type itself; this prevents us from using the shape in the returned type, which means we can't reconstruct the same shape on output.
This change is inline with how we treat array functions that return the sampe shape (like `map`).
The problem with this typing scheme is that it breaks non-piped ("function factory") dataLast invocations, where previously the type could be inferred from the param type of the callback (see test), but this is OK because that isn't a use-case we care about in the lib (as it doesn't seem very useful). This is the reason I called this a "feat" and not a "fix" in the semantic commits convention, so that it bumps the minor version and not just the patch version.

feat(forEach): pass complex array shapes thru the pipe

---

docs/src/components/migration-selector-island.tsx

I recently migrated to the second version. And I think these days this link is more important than migration from other libraries :)
---
---
- `test`: tests-only changes (transparent to …

docs: add migration guide in a more obvious place

---

src/isObjectType.ts

Closed https://github.com/remeda/remeda/issues/766
I'm not sure how it works, but `typedoc` generates different formats for a constant and a function, which is why the data in `data.json` for this function is different from the others and is filtered during the `transform` process.
---
---
- `perf`: changes to function implementations that improve a functions …

docs(isObjectType): fix typedoc

---

docs/src/components/migration-selector-island.tsx

The current label repeats the "migration" part which is already part of the menu title, and repeats the v2 part which isn't relevant for the viewer.

docs: shorten menu item label for v1 migration guide

---

src/shuffle.test-d.ts
src/shuffle.test.ts
src/shuffle.ts

Currently we reconstruct the output from the input member types.
Instead we can use the input type itself to build the output. This allows us to pass through qualities of the input like non-emptyness to the output.
In other words, shuffle should have the same return type as sortBy because it is effectively a sortBy a random number, so it can use the same return type.

feat(shuffle): Maintain input shape

---

docs/src/pages/index.mdx

Update the type hints (displayed as comments) to reflect that TypeScript does properly infer the types when using Remeda in this example.

docs: Updates type hints in functional data last example

---

.github/workflows/ci.yml
lint-staged.config.js
package.json
tsup.config.ts

Since #774 was shipped we have been including `test-d.ts` in our build artifact.
I also renamed the "typecheck" script to "check" to match the script that does the same thing in the docs project.

fix(build): remove test files from package

---

src/internal/types.test-d.ts
src/internal/types.ts
src/sample.test.ts
src/unique.ts
src/uniqueBy.ts
src/uniqueWith.ts

The unique functions return a simple array, ignoring the shape of the input. This means that some fidelity is lost when they are used in more complex computations. We can use some basic characteristics of a deduped array to improve the return type.
This isn't a perfect solution for all cases, as the test examples show, because we don't dedupe stuff at the type level, we just build the output based on the general character of the deduped array. This is intentional, so that the same type could be used for all uniqueXXX functions.

feat(unique, uniqueWith, uniqueBy): Use input shape to improve return type.

---

src/drop.test-d.ts
src/drop.ts
src/internal/types.ts

In #795 a better type for drop was introduced. This touched almost all cases, but still missed some nuances for suffix-arrays. Here I cover the remaining issues with that type.

fix(drop): an even more accurate return type for literal Ns

---

CODE_OF_CONDUCT.md

Using the template provided by GitHub.
Set my personal email as the point of contact for abuse reports.

docs: Add a Code of Conduct

---

src/internal/types.ts

The date came and went and type-fest haven't made the change. Because we can't guess when this will be fixed or if it will be fixed at all, it doesn't make sense to set an expiration for this.

chore: remove expiration date from TODO

---

docs/src/components/netlify-attribution.astro
docs/src/layouts/wiki.astro

Adds the netlify attribution badge to the main page.
Note that although this was added to the layout itself, this layout is only used on the main page atm. I felt this is a good place for it because it allowed me to separate the `footer` tag from the attribution itself, in case we want to add more stuff to the footer in the future.
This, together with #877 should satisfy the requirements for adding our docs site to the open-source plan.
Closes: #875

docs: add netlify attribution to main page

---

src/pick.test-d.ts
src/pick.ts

Allows the array of keys to be inferred from its values instead of from a wrapping param type.
Fixes: #886

fix(pick): better inference of picked keys

---

src/internal/types.ts
src/mean.test-d.ts
src/mean.test.ts
src/mean.ts

Related to #874, I have also integrated changes based on recent comments about `median` (e.g., removed type-guard related tests and modified the `Mean` type)
Please let me know if any additional adjustments are needed.

refactor(mean): drop `bigint` support

---

docs/src/content/mapping/ramda/__MISSING.md
docs/src/content/mapping/ramda/pluck.md

`pluck` is our most popular missing search result after `throttle`.

docs: add mapping entry for Ramda's `pluck`

---

src/mergeDeep.test-d.ts
src/mergeDeep.ts

Fixes #522.
We don't have a lot of type tests so I don't feel very confident about this change, but I can't think of a specific thing I expect to break with this change. The only reason record was used was because that was easy to understand, as long as the runtime doesn't complain about the lack of data coming from `object` (vs `Record`) than it's unlikely the types themselves break.
And we rely on type-fest for the heavy lifting; they probably handle interfaces well...

fix(mergeDeep): Support interfaces

---

src/split.test-d.ts
src/split.ts

A problem in type-fest's ArraySlice causes the issue (https://github.com/sindresorhus/type-fest/issues/982) but could be avoided in most cases by avoiding using ArraySlice when not needed.
This is a patch, and the problem would still exist when the optional limit param is used, but for the vast majority of usages of this utility, it should be enough to reduce the surface area of the issue, giving time for the issue to be resolved on the type-fest side.
Closes: #921

fix(split): split on literal unions with separator as a prefix

---

package-lock.json
package.json
src/internal/words.test.ts
src/internal/words.ts
src/toCamelCase.ts
src/toKebabCase.test-d.ts
src/toKebabCase.ts
src/toSnakeCase.test-d.ts
src/toSnakeCase.ts

Using the now exported `Words` utility from type-fest we can improve the typing for snake-case and kebab-case to take advantage of it.

fix(toSnakeCase, toKebabCase): literal types for literal strings

---

src/internal/types/TupleParts.test-d.ts
src/internal/types/TupleParts.ts
src/pick.test-d.ts
src/pick.ts

Expanding our TupleParts utility to allow easy access to the optional part of the prefix, and then using this to improve the type of pick so that optional keys are marked as optional in the output.
Closes: #911

fix(pick): support optional keys

---

src/stringToPath.ts

> Fix bad docstring for `stringToPath`
These seemingly reflected an old name for the function.
---
---
For scope put …

docs: correct docstring for stringToPath

---

docs/src/content/mapping/just/__MISSING.md
docs/src/content/mapping/just/extend.md
docs/src/lib/mappings.ts

Just is the biggest utility library after Lodash, Underscore and Ramda.

docs(just): Add a stub for migration guides from 'just'

---

src/uniqueWith.test.ts
src/uniqueWith.ts

Fixes #999 
- Previous implementation checked each item for a match that existed at a different index, skipping those. It checks the item's own equivalency as part of the implementation, but this can unexpectedly remove items due to interactions with the comparator's logic as shown in the issue.
- In the new implementation, the index equality check simultaneously handles this edge case and reduces unnecessary calls of the comparator.
---
---
- `fix`: changes to the runtime behavior of an …

fix(uniqueWith): return items that are not equal to themselves

---

src/ceil.test.ts
src/floor.test.ts
src/internal/withPrecision.ts
src/round.test.ts

The changes aim to increase the accuracy of the `floor`, `cail`, and `round` functions by using only integers when dividing and multiplying, avoiding floating point numbers.
Resolves #1003 
---
---
- `build`, …

fix(floor, ceil, round): do not divide and multiply by a floating point number

---

docs/src/pages/index.mdx

"Collaborative" instead of "Collabrative" :)

docs: fix a typo on homepage

---

.github/dependabot.yml

dependabot is misconfigured. We don't need to set the packages themselves because the lock file only sits in the monorepo root, and dependabot needs the lock file to send the correct update PR

chore(dependabot): remove package config

---

packages/remeda/src/countBy.test.ts
packages/remeda/src/countBy.ts
packages/remeda/src/groupBy.test.ts
packages/remeda/src/groupBy.ts

Closes https://github.com/remeda/remeda/issues/1046
---
---
For scope put the name of the function you are working on …

fix: Handling of strings that are `Object` instance method names (in`groupBy` and `countBy`)

---

packages/docs/src/content/mapping/lodash/debounce.md
packages/docs/src/content/mapping/lodash/throttle.md
packages/remeda/src/debounce.ts
packages/remeda/src/funnel.ts

Fix the incorrect GitHub link related to Lodash documentation, which appears to be caused by the monorepo refactoring.
And fix incorrect funnel api usage in lodash migration guide.
---
---
- `docs`: changes to the documentation of a …

docs: fix incorrect github link and incorrect funnel api usage

---

packages/remeda/src/evolve.ts

Corrected incorrect variable names in document comments.
---
---
For scope put the name of the function you are working …

docs(evolve): Correct variable name from `object` to `data` in example usage

---

packages/remeda/src/groupBy.bench.ts
packages/remeda/src/groupBy.ts

#1046 raised an issue with built-in props of the Object prototype interfering with how we build our object.
#1049 fixed this using a Map (which doesn't have props and entries in the same "namespace").
#1066 was an attempt to prefer objects over maps, but the perf didn't justify it.
I still felt that using a Map was the wrong call here because it only used the Map as an intermediate data structure and required recreating the output once it was done. In this PR, I suggest a better implementation that is significantly better performance-wise in almost all cases. This was achieved after extensive testing of many other similar implementations to pinpoint exactly what makes the engine purr and what makes it stutter.
The final implementation is 2x to 8x faster on some important real-life use …

fix(groupBy): Improve perf by using objects instead of Maps

---

packages/remeda/src/chunk.ts
packages/remeda/src/drop.test-d.ts
packages/remeda/src/drop.ts
packages/remeda/src/internal/types/PartialArray.ts
packages/remeda/src/internal/types/TupleParts.ts
packages/remeda/src/internal/types/TupleSplits.test-d.ts
packages/remeda/src/internal/types/TupleSplits.ts

Removing the deprecated TuplePrefix type and reimplementing the relveant types to handle optional items correctly.
important: chunk has only minor nits changed, it still doesn't handle optionals correctly.

fix(drop,partialBind): Fix types to handle optionals

---

packages/remeda/src/filter.test-d.ts
packages/remeda/src/filter.ts
packages/remeda/src/internal/types/FilteredArray.test-d.ts
packages/remeda/src/internal/types/FilteredArray.ts

Using the new TupleParts we can improve the return type for filter when used with a type-predicate. This allows us to consider every element in the input tuple shape and consider whether it could possibly be in the output or not.
Additionally we can also improve the result when filter is used with trivial predicates (that always return true, or always return false), allowing "short-circuit" style code where users effectively bypass the filtering via the predicate itself. 
The main type here was pulled out of the filter impl because it would be the basis (together with ArrayRequiredPrefix) for the groupByProp return type.

fix(filter): maintain tuple shape in result

---

packages/remeda/src/dropLastWhile.test-d.ts
packages/remeda/src/dropLastWhile.ts
packages/remeda/src/dropWhile.test-d.ts
packages/remeda/src/dropWhile.ts

#1076 introduced an error to the return type when `dropWhile` and `dropLastWhile` is used with a type-predicate. This PR reverts those changes until we can implement more accurate types.

fix(dropWhile, dropLastWhile): revert #1076

---

.github/workflows/publish-jsr.yml

We need to trigger a full release so that we get a git tag with a version that includes the jsr.json file we can use when running our release script; otherwise, we cannot debug the release script.

fix(jsr.io): trigger release

---

README.md
packages/README.md
packages/docs/src/components/install-commands.astro
packages/remeda/README.md

Also added a readme for the packages root because otherwise GitHub use the one under /docs because an unfortunate fallback path by github :( (
> If you put your README file in your repository's hidden .github, root, **or docs directory**, GitHub will recognize and automatically surface your README to repository visitors.
> If a repository contains more than one README file, then the file shown is chosen from locations in the following order: the .github directory, then the repository's root directory, **and finally the docs directory**.

docs: deno/jsr.io install command

---

.github/workflows/ci-library.yml

The job fails with a cryptic message:
>     Invalid symbol 45, offset 1102.
It's not clear where this is coming from as it doesn't reproduce locally and it seems that the publish actually succeeds.
Adding the --verbose flag to try and get more info.

chore(jsr): add verbose flag to debug failing jobs

---

.github/workflows/ci-library.yml
packages/remeda/package.json

From reading the code for the publish command, I learned that:
* there's a --set-version flag which allows us to tell JSR what version we are publishing instead of mutating the JSR file
* The job succeeds by ignoring versions that have already been published, making our optimization unnecessary.
Also waiting on some guidance with the provenance errors as reported in: https://github.com/denoland/deno/issues/29671

chore(jsr): simplify jsr job

---

packages/remeda/src/internal/types/EnumerableStringKeyedValueOf.test-d.ts
packages/remeda/src/internal/types/EnumerableStringKeyedValueOf.ts

Fixes #1122
I tested it with the rerpo I put in the issue via the sandbox playground and got the correct types.

fix(forEachObj,mapKeys,mapValues,omitBy,pickBy,values): support paramerized record keys

---

packages/remeda/src/pickBy.test-d.ts
packages/remeda/src/pickBy.ts

We were handling unbounded records for the non-narrowing case, but didn't address the typing for unbounded records for the narrowing case. The solution is similar, where we need to reconstruct the record, but this time we also need to extract the narrowed type from the original type.
Fixes: #1075

fix(pickBy): dont add `undefined` to value type of unbounded records

---

.github/workflows/ci-library.yml

the workflow relies on tag data being available, but the default fetch action has an explicit --no-tags flag when fetching.

chore(jsr): fix workflow to fetch tags

---

.github/workflows/ci-library.yml
packages/remeda/jsr.json

We inject the version manually via a cli flag, but it would fail if the jsr.json file itself already has a version.

chore(jsr): remove version from jsr.json

---

packages/remeda/src/setPath.test-d.ts
packages/remeda/src/setPath.ts

Fixes: #990
Everything in typescript is an object (kinda) so we don't need to check it in the condition and instead assume that users aren't doing something weird (but even then try to make it work for them via whatever TypeScript defines as the keyof for that thing).
Additionally we had a minor issue with arrays where a partial path wouldn't match properly because of a missing `readonly` which prevents readonly tuples from satisfying the result.

fix(setPath): support interfaces

---

packages/docs/src/layouts/base.astro

When the search modal disables scrolling, it messes with the alignment of the primary content because it uses the body-tag to for its `container mx-auto` classes. Moving these to a child allows the algoria search modal to disable the scroll without messing with the content.
Resolves #1147.

docs: fix alignment issue caused by search modal

---

packages/docs/src/components/search.tsx

Algolia are reseting the page scroll position when searching within the same page (e.g., /docs/) after the URL already has a hash.
This bug is also apparent in other Algolia DocSearch based sites so it's not internal to our site, but we can workaround it.
Fixes: #1155

docs(docsearch): fix same-page keyboard searches

---

packages/docs/src/components/migration-selector-island.tsx

The click area of the links in the migrations dropdown doesn't match it's visual space as well as its hover-state. Making it easy to miss the link, but the dropdown still closes, so it feels weird.
Example:
This makes the dropdown element be the anchor itself, so it takes all the space, and matches the visual size.

docs: fix click surface for migration dropdown links

---

.github/workflows/ci-library.yml
.github/workflows/pr_titles.yml

Following this github blog post: https://github.blog/changelog/2025-07-31-npm-trusted-publishing-with-oidc-is-generally-available/ and this npm docs page: https://docs.npmjs.com/trusted-publishers
using "fix" as the semantic label to allow the release to go through so we can see it works.

fix(npm): use oidc when publishing to npm

---

.github/workflows/ci-library.yml
packages/remeda/package.json

Not supported yet: https://github.com/semantic-release/npm/issues/958

fix(release): revert OIDC release (for now) + jsr provenance
