remeda/remeda

src/allPass.test.ts
src/allPass.ts

Add support for `allPass`, as seen in Ramda: https://ramdajs.com/docs/#allPass

Add allPass

---

src/forEachObj.test.ts
src/forEachObj.ts

Added forEachObjIndexed, based on [ramda's implementation](https://ramdajs.com/docs/#forEachObjIndexed)

Added R.forEachObjIndexed

---

mapping.md
src/index.ts
src/times.test.ts
src/times.ts

* Add times function & tests
* Update mapping.md

Add times-function

---

src/first.test.ts
src/first.ts
src/last.ts

Add undefined return type to first and last

---

src/drop.ts
src/forEachObj.ts

* Fix function description for data-first drop()Tiny doc fix for data-first drop()
* Fix signature typo in forEachObj

Misc jsdoc fixes

---

mapping.md

Add one-liners to mapping.md

---

src/addProp.ts
src/forEachObj.ts
src/mapValues.ts
src/omit.ts
src/pick.ts

Fixes type declarations to accept interfaces

---

src/reduce.ts

Fix reduce.indexed return type

---

docs/src/data.json
src/findIndex.ts

fix(docs): correct findIndex example

---

src/guards.ts

fix(guards): get rid of ts-expect-error for isPromise guard

---

mapping.md
src/index.ts
src/pickBy.test.ts
src/pickBy.ts

Add pickBy, like in [Ramda](https://ramdajs.com/docs/#pickBy) or [Lodash](https://lodash.com/docs/4.17.15#pickBy). Due to TS limitations I've added types for Record-like objects only

Add pickBy

---

src/index.ts

Fixes https://github.com/remeda/remeda/pull/180#issuecomment-1186212647

Add differenceWith to index

---

README.md

Replace broken dependencies badge.
Replace all bages with shield.io badges to make them look the same:
---

chore: Fix badges

---

.github/workflows/ci.yml

Remove `--dry-run` from ci action
---

chore: Remove dry-run

---

docs/css/app.scss
docs/src/FnDoc.tsx
docs/src/Home.tsx
docs/src/Menu.tsx
scripts/generate.ts
src/keys.test.ts
src/keys.ts
src/values.ts

feat: add strict version to keys where the return type is a union of the input

---

mapping.md

Updating `mapping.md` for missing `isNil` / `identity` support.
---

docs: update mapping.md

---

mapping.md
src/index.ts
src/omitBy.test.ts
src/omitBy.ts
src/pickBy.test.ts
src/pickBy.ts

Closes #202. Made from `pickBy`
---

feat: Add omitBy

---

README.md

chore: fix github badge

---

docs/src/Header.tsx

https://github.com/antfu/case-police
---

docs: Github -> GitHub

---

docs/src/Home.tsx

Improved 2 sentences inside the documentation.
---
Make sure that you: (not applicable for this PR)

docs: improve two sentences

---

src/sortBy.test.ts
src/sortBy.ts

chore(sortBy): better type inference for data last

---

.github/workflows/ci.yml
.github/workflows/pages.yml

chore: fix node versions

---

.eslintrc.js
src/clone.test.ts
src/clone.ts
src/countBy.ts
src/equals.ts
src/findLastIndex.test.ts
src/flatMapToObj.ts
src/forEach.test.ts
src/forEachObj.ts
src/groupBy.ts
src/guards.test.ts
src/guards.ts
src/indexBy.ts
src/mapKeys.test.ts
src/mapToObj.ts
src/mapValues.test.ts
src/maxBy.ts
src/minBy.ts
src/partition.ts
src/pipe.ts
src/sort.ts
src/zip.ts

Removing the blob of TODOs for trivial manual fixes.
Each commit is a different rule, to make reviewing easier

chore(lint): trivial manual fixes

---

src/pipe.ts

There's no reason to limit the size (length? depth?) or a pipe, it should technically be able to accommodate any computation complexity.

chore(pipe): more ops

---

src/differenceWith.test.ts
src/drop.test.ts
src/filter.test.ts
src/find.test.ts
src/findIndex.test.ts
src/first.test.ts
src/flatMap.test.ts
src/flatten.test.ts
src/flattenDeep.test.ts
src/reject.test.ts
src/uniq.test.ts
src/uniqBy.test.ts
src/uniqWith.test.ts
test/lazy_invocation_counter.ts
tsconfig.json

We are building and distributing this test-only internal util because it is part of our src folder.
I don't have a lot of experience with testing modules, but a `test` dir for utils seems like a convention.
I also renamed the component a bit to make it a little clearer what it does, it was always confusing to me.

test: extract counter

---

src/stringToPath.ts

Just cleaning up so it doesn't show up on every PR

chore: fix lint warning

---

src/index.ts
src/sliceString.test.ts
src/sliceString.ts

This just makes it easier to process strings in a pipe without needing to manually create an arrow function just for slicing.
---

feat: add sliceString function

---

src/_types.ts
src/mapValues.test.ts
src/mapValues.ts
src/toPairs.ts

Closes https://github.com/remeda/remeda/issues/354

improve mapValues types

---

mapping.md
src/setPath.ts

- docs: improve set, setPath docs 87599f40bed143658855481d3a771a96e20e81de
- refactor: rename variable a152db91d27467856b8373b2c463fc0f062a3248
---
---
- `feat`: new functions!
- `fix`: changes to function implementations that fix a bug where a function produces the wrong _runtime_ results.
- `type`: type-only changes (params, overloading, return types, etc...)
- `test`: tests-only changes …

refactor(setPath): change variable name, and change docs of `set`, `setPath`

---

src/_paths.ts
src/chunk.ts
src/first.ts
src/fromPairs.ts
src/groupBy.ts
src/hasAtLeast.ts
src/isBoolean.ts
src/isNumber.ts
src/isString.ts
src/join.ts
src/keys.ts
src/reverse.ts
src/sample.ts
src/stringToPath.ts
src/swapIndices.ts
src/type.ts
src/zip.ts

Following a recent update to prettier, we need to reformat our project using the new prettier.

style: reformat project with updated prettier

---

.vscode/settings.json

This is cool; I saw it first in the Next.JS repo. I didn't know this existed.

chore(vscode): Fold test files under the implementation 

---

docs/lint-staged.config.js

Add type checking and more prettier

chore: better lint-staged

---

.github/dependabot.yml
package-lock.json
package.json
src/clone.test.ts
src/fromPairs.test.ts
src/join.test.ts
src/mapValues.test.ts
src/zip.test.ts
tsconfig.dist.json
tsconfig.json
vitest.config.ts

Mainly to update vitest to version 1, which includes some fixes to type assertions and benchmarking.
Also bumps our typescript version

build: update dependencies

---

.github/workflows/ci.yml
package-lock.json
package.json

Better control over the version of the semantic-release tool, and documents our release process more clearly

ci: install semantic-release locally

---

mapping.md
src/debounce.test.ts
src/debounce.ts
src/index.ts
tsconfig.json

Closes #419
Inspired by the lodash implementation (https://github.com/lodash/lodash/blob/main/src/debounce.ts).
Tests were copied from lodash too (https://github.com/lodash/lodash/blob/main/test/debounce.spec.js), but the latest version of their test has some issues, and I'm not sure their tests actually run (I didn't try).
---
---
- `feat`: new functions!
- `fix`: changes to function implementations that fix a bug where a function produces the wrong _runtime_ results.
- `type`: type-only changes (params, overloading, return types, etc...)
- `perf`: changes to function …

feat(debounce): add debounce function

---

mapping.md
src/add.test.ts
src/add.ts
src/divide.test.ts
src/divide.ts
src/index.ts
src/multiply.test.ts
src/multiply.ts
src/subtract.test.ts
src/subtract.ts

This PR introduces four new number functions: `R.add`, `R.subtract`, `R.multiply` and `R.divide`.
Closes #439.
---
---
- `test`: tests-only changes (transparent to users of the …

feat: Add R.add, R.subtract, R.multiply and R.divide functions

---

src/hasAtLeast.ts

docs(hasAtLeast): Fix dataLast example

---

docs/src/components/function-card.astro
docs/src/layouts/layout.astro
docs/src/pages/docs.astro

Fixes layout, scroll margin and changes example text media query to **lg:text-base** from **md:text-base**

docs: fix layout

---

docs/.vscode/settings.json
docs/scripts/transform.ts
docs/src/components/code-block.astro
docs/src/components/install-commands.astro
docs/src/pages/index.astro

Cleaning up the transform script step by step. This time, prettier.

docs: move prettier to astro

---

docs/README.md

I wanted to remove this in #451 and forgot

docs: remove mentioning of transform script

---

src/omit.test.ts
src/omit.ts
src/pick.test.ts
src/pick.ts

closes #504
---
---
- `build`, …

fix(pick|omit): Fix type inference in pipe

---

mapping.md

…sNotNil` in Ramda
---
---
- `docs`: changes to the …

docs(isDefined): Update `mapping.md`

---

mapping.md

---
---
- `docs`: changes to the documentation of a function …

docs: Add documentation links to `mapping.md`

---

docs/src/components/function-card.astro
docs/src/lib/transform.ts
docs/typedoc.json

add a link to the function source on the top-right of the function card

docs: link function sources

---

mapping.md

Minor PR, just noticed mapValues didn't have an entry.
---
---
- `docs`: changes to the documentation of a function …

docs(mapValues): Update missing mappings entry for `mapValues`

---

eslint.config.js
src/clone.test.ts
src/clone.ts
src/debounce.test.ts
src/debounce.ts
src/flatten.ts
src/flattenDeep.ts
src/groupBy.ts
src/pick.ts
src/pipe.ts
src/setPath.ts

finishing the cleanup of lint supressions

fix: remaining lint issues in project

---

docs/src/components/navbar.tsx

This PR adds ability to filter in the sidebar (navbar) by a category like on Lodash docs or Ramda docs.
https://github.com/remeda/remeda/assets/10157660/7c7b8f00-2ba1-4910-b258-52c9ad296632

docs: add ability to filter by category in sidebar

---

.github/workflows/ci.yml

---
---
- `docs`: changes to the documentation of a function …

chore: run CI on the beta branch

---

package.json

See https://arethetypeswrong.github.io/?p=remeda%402.0.0-beta.17

fix(build): Fix: Masquerading as ESM lint issue

---

.github/workflows/ci.yml
package-lock.json
package.json

build: Add publint and attw to the ci

---

src/conditional.test.ts
src/conditional.ts

fix(conditional): default case return value was ignored.

---

.github/workflows/codecov.yml
src/_heap.test.ts
src/_heap.ts
src/clone.test.ts
src/clone.ts
src/debounce.ts
src/evolve.test.ts
src/flatMap.test.ts
src/omit.test.ts
src/pipe.ts
src/setPath.ts
src/sliceString.test.ts
src/stringToPath.test.ts
src/stringToPath.ts
src/swapIndices.test.ts
src/take.test.ts
src/take.ts
src/zipWith.ts
vitest.config.ts

Bumping our coverage to 100% in v2.

fix(coverage): 100% coverage

---

mapping.md

docs(sortedUniq): add one-liner solution

---

eslint.config.mjs
src/isDeepEqual.test.ts
src/isDeepEqual.ts

Add support for maps for the isDeepEqual function
Fixes: #626

feat(isDeepEqual): add support for maps 

---

mapping.md
src/_utilityEvaluators.ts
src/difference.test.ts
src/difference.ts
src/intersection.test.ts
src/intersection.ts
src/isIncludedIn.test.ts

Adding a variant difference for multiset semantics and update the deprecation warning.

feat(difference, intersection): add multiset variants

---

eslint.config.mjs
src/isDeepEqual.test.ts
src/isDeepEqual.ts

feat(isDeepEqual): add supports for Set

---

eslint.config.js
src/isDeepEqual.test.ts
src/isDeepEqual.ts

feat(isDeepEqual): cherry-pick #640

---

docs/src/content/v1-migration/compact.md
docs/src/content/v1-migration/concat.md
docs/src/content/v1-migration/countBy.md
docs/src/content/v1-migration/createPipe.md
docs/src/content/v1-migration/difference.md
docs/src/content/v1-migration/dropLastWhile.md
docs/src/content/v1-migration/filter.md
docs/src/content/v1-migration/find.md
docs/src/content/v1-migration/findIndex.md
docs/src/content/v1-migration/findLast.md
docs/src/content/v1-migration/findLastIndex.md
docs/src/content/v1-migration/flatMap.md
docs/src/content/v1-migration/flatMapToObj.md
docs/src/content/v1-migration/flatten.md
docs/src/content/v1-migration/flattenDeep.md
docs/src/content/v1-migration/forEach.md
docs/src/content/v1-migration/forEachObj.md
docs/src/content/v1-migration/fromEntries.md
docs/src/content/v1-migration/fromKeys.md
docs/src/content/v1-migration/fromPairs.md

There's a lot of functions starting with F which had changes

docs: Migration Guide, F

---

.vscode/extensions.json
.vscode/settings.json
docs/.vscode/extensions.json
docs/.vscode/settings.json

Recommended extensions and some settings

chore(vscode): make sure vscode is set up for success

---

release.config.js

BREAKING CHANGE: This should release v2.

build: Include main in branches

---

docs/src/components/header.astro
docs/src/components/nav-link.astro
docs/src/layouts/docs-page.astro
docs/src/layouts/wiki.astro

The layout is broken when viewed on mobile. It's still broken even with this fix but it looks better.
This PR is just a clone of #695 which was merged to master

docs(mobile): fix layout

---

docs/src/lib/get-tags.ts
docs/src/lib/transform.ts
eslint.config.js
src/difference.ts
src/differenceWith.ts
src/drop.ts
src/filter.ts
src/find.ts
src/first.ts
src/flat.ts
src/flatMap.ts
src/forEach.ts
src/intersection.ts
src/intersectionWith.ts
src/invert.ts
src/keys.ts
src/last.ts
src/map.ts
src/mapWithFeedback.ts
src/only.ts
src/sample.ts
src/take.ts
src/unique.ts
src/uniqueBy.ts
src/uniqueWith.ts
src/values.ts
src/zip.ts
src/zipWith.ts

The "pipeable" tag is confusing for people, it's just the wrong term for what it tries to communicate. It was also erronously put on several non-lazy functions, and was missing from one.

docs: pipeable -> lazy

---

src/isNullish.test.ts
src/isNullish.ts

This addresses https://github.com/remeda/remeda/issues/675#issuecomment-2155230051, but it doesn't yet fix conditional or the issue raised in that issue.

fix(isNullish): better type narrowing

---

package-lock.json
package.json
src/groupBy.test.ts
src/internal/types.test.ts
src/internal/types.ts
src/omitBy.ts
src/pickBy.ts

fix: Don't return partial for branded or template keys

---

docs/src/pages/index.mdx

I don't want people to mis-read it as "expensive" so changing the wording.

docs(index): Expansive -> Useful

---

docs/package-lock.json
docs/package.json
docs/src/lib/mappings.ts
docs/vite.scripts.config.ts

docs: Update Remeda + Fix Todos

---

docs/src/components/function-description.astro
docs/src/components/install-commands.astro
docs/src/components/mapping-function-card.astro
docs/src/components/smart-link.astro
docs/src/layouts/base.astro
docs/src/layouts/docs-page.astro

The docs don't render well on mobile, this was due to weird interactions with overflows.
The docs also didn't look good on extra large viewports because they would stretch.

docs: Fix layout issues for mobile

---

docs/src/content/mapping/lodash/__MISSING.md
docs/src/content/mapping/lodash/isArray.md
docs/src/content/mapping/lodash/isBoolean.md
docs/src/content/mapping/lodash/isDate.md
docs/src/content/mapping/lodash/isError.md
docs/src/content/mapping/lodash/isFunction.md
docs/src/content/mapping/lodash/isNumber.md
docs/src/content/mapping/lodash/isString.md

docs(lodash): Add mapping for isXXX guards

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json

Bumping typescript for the project and our testing matrix.
Also bumped other dependencies.

chore: TypeScript 5.5

---

CONTRIBUTING.md
README.md
docs/README.md

quite opinionated (especially in the philosophy section), so push back if you disagree on anything or if you want something added

chore: add `CONTRIBUTING.md`

---

docs/src/content/v1-migration/clone.md

---
---
- `docs`: changes to the documentation of a function …

docs(clone): fix typo in v1 migration

---

src/times.ts

Closed https://github.com/remeda/remeda/issues/765 
---
---
- `docs`: changes to the documentation of a function **or …

docs(times): fix typedoc

---

src/isStrictEqual.ts

Reported in: https://github.com/remeda/remeda/pull/773#discussion_r1671324846

docs(isStrictEqual): Fix isEqual -> isStrictEqual in docs

---

.gitignore

Closes #808
---
---
- `build`, …

chore: ignore `tsconfig.vitest-temp.json` file from git

---

src/dropLast.test.ts
src/dropLast.ts
src/takeLast.test.ts
src/takeLast.ts

fix(dropLast, takeLast): handle overflows

---

README.md

docs(readme): add contributors

---

docs/src/content/mapping/lodash/camelCase.md
src/toCamelCase.ts

docs(toCamelCase): add examples and signature for the optional `preserveConsecutiveUppercase` flag

---

src/range.ts

Fix typo
---
---
- `docs`: changes to the documentation of a …

docs(range): fix typo

---

src/clone.ts

docs(clone): add supported types

---

src/clone.ts

docs(clone): make the list of supported types clearer

---

src/splice.test.ts

Replace the test.each block with concrete describe and tests with proper names.

test(splice): split each block to individual tests

---

src/isEmpty.test-d.ts
src/isEmpty.ts

Support interface types.
Closes #879

fix(isEmpty): support interfaces

---

docs/src/content/mapping/ramda/__MISSING.md
docs/src/content/mapping/ramda/median.md
src/index.ts
src/median.test-d.ts
src/median.test.ts
src/median.ts

Related to #874. Please let me know if any further adjustments are needed.
---
---

feat(median): Add median

---

.github/pull_request_template.md
.github/workflows/pr_titles.yml

Removing labels we don't want to use.

chore: semantic commit levels

---

.github/FUNDING.yml

I didn't notice the file is a yml, it needs to have proper yml syntax.

chore: fix FUNDING.yml

---

.github/FUNDING.yml

Use the remeda sponsored page instead of personal ones

chore: Update FUNDING.yml

---

src/internal/words.ts

Closes #928.
---
---
For scope put the name of the function you are working on (either new or
existing).
</details>

fix(toCamelCase, toSnakeCase, toKebabCase): Support iOS 16.3-

---

docs/src/content/mapping/ramda/__MISSING.md
docs/src/content/mapping/ramda/countBy.md
src/countBy.test-d.ts
src/countBy.test.ts
src/countBy.ts
src/index.ts

Related to #885. It would be nice to have this utility so I decided to give it a try :)
I would be happy to make any further adjustments as needed.
---

feat(countBy): Add countBy

---

docs/src/lib/transform.ts
src/add.ts
src/endsWith.ts
src/startsWith.ts
src/stringToPath.ts
src/swapIndices.ts
src/toCamelCase.ts

closes #815, closes #979, closes #980, closes #981, closes #982

docs: various small docs fixes

---

packages/remeda/src/pipe.test-d.ts
packages/remeda/src/pipe.test.ts
packages/remeda/src/pipe.ts

fix(pipe): Allow usage with 0 functions

---

.github/workflows/ci-library.yml

We need to quote the version string.

chore(jsr.io): fix workflow

---

.github/workflows/ci-library.yml

Unfortunatly it is really hard to test the action because it depends on the repo state too much, the only way is to send out additional PRs with fixes.
:(

chore(jsr): Another fix for the publish job

---

packages/docs/src/content/mapping/lodash/__MISSING.md
packages/docs/src/content/mapping/lodash/without.md

docs(lodash): without

---

packages/remeda/src/values.ts

docs(values): fix typo

---

packages/remeda/src/partialBind.ts
packages/remeda/src/partialLastBind.ts

docs(partialBind,partialLastBind): fix examples

---

packages/docs/.vscode/settings.json
packages/docs/src/components/function-card.astro

docs: sort dataFirst and dataLast signatures

---

package-lock.json
packages/docs/eslint.config.ts
packages/docs/package.json
packages/docs/src/components/article.astro
packages/docs/src/components/code-block.astro
packages/docs/src/components/copy-button.tsx
packages/docs/src/components/docs-page-nav.astro
packages/docs/src/components/function-api.astro
packages/docs/src/components/function-card.astro
packages/docs/src/components/function-description.astro
packages/docs/src/components/github-edit.astro
packages/docs/src/components/github-logo-icon.astro
packages/docs/src/components/github-source.astro
packages/docs/src/components/header.astro
packages/docs/src/components/install-commands.astro
packages/docs/src/components/mapping-function-card.astro
packages/docs/src/components/markdown.astro
packages/docs/src/components/migration-selector-island.tsx
packages/docs/src/components/mobile-nav.tsx
packages/docs/src/components/navbar.tsx
packages/docs/src/components/netlify-attribution.astro
packages/docs/src/components/prose.astro
packages/docs/src/components/search.tsx
packages/docs/src/components/theme-switcher.tsx
packages/docs/src/components/themed-code.astro
packages/docs/src/components/v1/function-card.astro
packages/docs/src/layouts/docs-page.astro
packages/docs/src/pages/docs.astro
packages/docs/src/pages/migrate/[library].astro
packages/docs/src/pages/migrate/v1.astro

docs(lint): lint astro files + more rules

---

packages/remeda/src/swapProps.ts

---
---
For scope put the name of the function you are working …

docs(swapProps): Update method name in jsdoc

---

.gitignore
packages/docs/src/content/mapping/lodash/__MISSING.md
packages/docs/src/content/mapping/lodash/difference.md
packages/docs/src/content/mapping/lodash/differenceBy.md
packages/docs/src/content/mapping/lodash/differenceWith.md
packages/docs/src/content/mapping/lodash/pull.md
packages/docs/src/content/mapping/lodash/pullAll.md
packages/docs/src/content/mapping/lodash/pullAllBy.md
packages/docs/src/content/mapping/lodash/pullAllWith.md
packages/docs/src/content/mapping/lodash/without.md
packages/remeda/src/differenceWith.ts

Closes: #1185
* Add more mapping documents and rework the whole section for lodash pullXXX, without, and differenceXXX functions.
* Slight changes and fixes to the differenceWith remeda function docs.

docs(pull): rewrite Lodash pullXXX and differenceXXX mapping docs

---

packages/docs/src/content/mapping/lodash/difference.md
packages/docs/src/content/mapping/lodash/differenceBy.md
packages/docs/src/content/mapping/lodash/differenceWith.md
packages/docs/src/content/mapping/lodash/pull.md
packages/docs/src/content/mapping/lodash/pullAll.md
packages/docs/src/content/mapping/lodash/pullAllBy.md
packages/docs/src/content/mapping/lodash/pullAllWith.md

docs(difference): minor nits and corrections

---

.github/workflows/ci-library.yml
.github/workflows/pr_titles.yml

See the failure logs here: https://github.com/remeda/remeda/actions/runs/17574211958/job/49915995481

fix(semantic-release): provide a github token in the env

---

packages/docs/src/content/mapping/lodash/zipObject.md
packages/docs/src/content/mapping/ramda/zipObj.md

docs: fix broken links in migration articles

---

packages/docs/src/components/github-edit.astro
packages/docs/src/content/mapping/lodash/camelCase.md
packages/docs/src/content/mapping/lodash/kebabCase.md
packages/docs/src/content/mapping/lodash/snakeCase.md

docs: even more broken links
